AllCops:
  Exclude:
    - vendor/**/*

AbcSize:
  Max: 25
BlockLength:
  Enabled: false
Documentation:
  Enabled: false
FileName:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 175
