AllCops:
  Exclude:
    - vendor/**/*

AbcSize:
  Enabled: false
BlockLength:
  Enabled: false
Documentation:
  Enabled: false
FileName:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 175
MethodLength:
  Max: 20
