AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*

AbcSize:
  Enabled: false
BlockLength:
  Enabled: false
BlockNesting: 
  Max: 4
ClassLength:
  Enabled: false
ClassVars:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
FileName:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 175
MethodLength:
  Enabled: false
ModuleLength:
  Enabled: false